build:
  image: gliderlabs/alpine:3.4
  environment:
    GOPATH: "/dev/go/amp-pilot"
  commands:
    - apk-install bash go bzr git mercurial subversion openssh-client ca-certificates
    - mkdir -p /go/src /go/bin && chmod -R 777 /go
    - cd /dev/go/amp-pilot/src && go build -o ../bin/amp-pilot.alpine
