version: '2'
services:
  amp-pilot:
    image: appcelerator/amp-pilot:latest
    build: .
    environment:
      CONSUL: consul:8500
  # store
  consul:
    image: appcelerator/consul:latest-server
    hostname: consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    command:
      [ "-bootstrap"]

  zookeeper:
    image: appcelerator/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock      
      - /bin/amppilot:/bin/amppilot
    environment:
      CONSUL: consul:8500
    depends_on:
      - consul

  kafka:
    image: appcelerator/kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      CONSUL: consul:8500
      TOPIC_LIST: "amp-logs amp-service-start amp-service-stop amp-service-terminate amp-service-scale amp-docker-events amp-service-events telegraf"
    depends_on:
      - zookeeper

  ## logging

  amp-log:
    image: appcelerator/amp-log:latest
    ports:
      - "4018:3000"
    environment:
      DEBUG: lib*,app*
      CONSUL: consul:8500
      ZOOKEEPER: zookeeper:2181

  amp-monitor:
    image: appcelerator/amp-monitor:latest
    ports:
      - "4018:3000"
    environment:
      DEBUG: lib*,app*
      CONSUL: consul:8500
      ZOOKEEPER: zookeeper:2181

  elasticsearch:
    image: appcelerator/elasticsearch-amp:latest
    ports:
    - 9200:9200
    - 9300:9300
    environment:
      CONSUL: consul:8500
    depends_on:
    - consul

  nginx:
    image: appcelerator/amp-ui:latest
    ports:
    - 80:80
    environment:
      CONSUL: consul:8500
