#!/bin/sh

FILE_U=/etc/issue.net
FILE_D=/etc/debian_version
BIN1=/bin/amppilot/amp-pilot.alpine
BIN2=/bin/amppilot/amp-pilot.amd64

echo "pilotLoader launched"
if [ ! -f $BIN1 ]
then
	echo "waiting for "$BIN1
	sleep 5
fi
if [ ! -f $BIN2 ]
then
	echo "waiting for "$BIN2
	sleep 5
fi

if [ ! -f $BIN1 ]
then
	exit 1
fi
if [ ! -f $BIN2 ]
then
	exit 1
fi

echo "binaries ready"
if [ -f $FILE_U ]
then
	echo "Launch amp-pilot.amd64"
        exec /bin/amppilot/amp-pilot.amd64 $*
else
	if [ -f $FILE_D ]
	then
		echo "Launch amp-pilot.amd64"
		exec /bin/amppilot/amp-pilot.amd64 $*
	else
		echo "Launch amp-pilot.alpine"
		exec /bin/amppilot/amp-pilot.alpine $*
	fi
fi
